# Generated by Django 3.0.8 on 2020-07-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
