# Generated by Django 3.0.8 on 2020-07-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200726_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likedBy',
            new_name='liked',
        ),
    ]
