# Generated by Django 3.0.8 on 2020-07-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200726_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='network.Post'),
            preserve_default=False,
        ),
    ]
