# Generated by Django 3.0.8 on 2020-07-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Post'),
        ),
    ]
